# Generated by Django 5.2.14 on 2026-08-01 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_product_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProbabilityDistribution',
            fields=[
                ('probability_id', models.AutoField(primary_key=True, serialize=False)),
                ('demand_value', models.PositiveIntegerField()),
                ('demand_frequency', models.PositiveIntegerField()),
                ('demand_probability', models.DecimalField(decimal_places=4, max_digits=10)),
                ('demand_cumulative_probability', models.DecimalField(decimal_places=4, max_digits=10)),
                ('demand_random_interval', models.CharField(max_length=20)),
                ('lead_time_days', models.PositiveIntegerField()),
                ('lead_frequency', models.PositiveIntegerField()),
                ('lead_probability', models.DecimalField(decimal_places=4, max_digits=10)),
                ('lead_cumulative_probability', models.DecimalField(decimal_places=4, max_digits=10)),
                ('lead_random_interval', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='probability_distributions', to='product.product')),
            ],
            options={
                'db_table': 'probability_distribution',
                'ordering': ['probability_id'],
            },
        ),
    ]
