# Generated by Django 6.0.4 on 2026-08-01 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('probability', '0001_initial'),
        ('product', '0004_alter_product_supplier'),
    ]

    operations = [
    ]
