# Generated by Django 5.2.14 on 2026-08-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('probability', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='probabilitydistribution',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='probabilitydistribution',
            name='demand_cumulative_probability',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='probabilitydistribution',
            name='demand_frequency',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='probabilitydistribution',
            name='demand_probability',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='probabilitydistribution',
            name='demand_random_interval',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='probabilitydistribution',
            name='demand_value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='probabilitydistribution',
            name='lead_cumulative_probability',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='probabilitydistribution',
            name='lead_frequency',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='probabilitydistribution',
            name='lead_probability',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='probabilitydistribution',
            name='lead_random_interval',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='probabilitydistribution',
            name='lead_time_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
