# Generated by Django 5.2.14 on 2026-08-01 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('probability', '0002_probabilitydistribution_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='probabilitydistribution',
            name='updated_at',
        ),
    ]
