# Generated by Django 5.2.14 on 2026-08-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('probability', '0003_remove_probabilitydistribution_updated_at'),
    ]

    operations = [
        migrations.RunSQL("DELETE FROM probability_distribution;", reverse_sql=migrations.RunSQL.noop),
        migrations.AlterField(
            model_name='probabilitydistribution',
            name='demand_cumulative_probability',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='probabilitydistribution',
            name='demand_frequency',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='probabilitydistribution',
            name='demand_probability',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='probabilitydistribution',
            name='demand_random_interval',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='probabilitydistribution',
            name='demand_value',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='probabilitydistribution',
            name='lead_cumulative_probability',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='probabilitydistribution',
            name='lead_frequency',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='probabilitydistribution',
            name='lead_probability',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='probabilitydistribution',
            name='lead_random_interval',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='probabilitydistribution',
            name='lead_time_days',
            field=models.JSONField(default=list),
        ),
    ]
