# Generated by Django 6.0.4 on 2026-08-05 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('probability', '0002_probabilitydistribution_product'),
        ('probability', '0004_alter_probabilitydistribution_demand_cumulative_probability_and_more'),
    ]

    operations = [
    ]
