# Generated by Django 5.2.15 on 2026-08-05 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('probability', '0005_merge_20260805_1241'),
        ('product', '0005_remove_historicalproduct_opening_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probabilitydistribution',
            name='product',
            field=models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='probability_distributions', to='product.product'),
        ),
    ]
