# Generated by Django 5.2.15 on 2026-08-05 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('probability', '0005_merge_20260805_1239'),
        ('probability', '0006_alter_probabilitydistribution_product'),
    ]

    operations = [
    ]
