# Generated by Django 5.2.15 on 2026-08-07 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('probability', '0005_merge_20260805_1232'),
        ('probability', '0007_merge_20260805_1734'),
    ]

    operations = [
    ]
