# Generated by Django 6.0.4 on 2026-07-31 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reset_otp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalcustomuser',
            name='reset_otp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
