# Generated by Django 6.0.4 on 2026-08-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser_reset_otp_historicalcustomuser_reset_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='reset_otp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcustomuser',
            name='reset_otp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
