# Generated by Django 6.0.4 on 2026-08-03 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_customuser_reset_otp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='historicalcustomuser',
            name='name',
        ),
    ]
