# Generated by Django 5.2.15 on 2026-08-11 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalCustomUser',
        ),
    ]
