# Generated by Django 5.2.15 on 2026-08-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
