# Generated by Django 6.0.4 on 2026-08-04 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0003_historicalorganization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['admin_id', 'organization_id'], 'verbose_name': 'Organization', 'verbose_name_plural': 'Organizations'},
        ),
    ]
