# Generated by Django 5.2.15 on 2026-08-05 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notification',
            table='notification',
        ),
    ]
