# Generated by Django 5.2.15 on 2026-08-13 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlogs', '0002_alter_auditlog_options_alter_auditlog_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='module',
            field=models.CharField(blank=True, default='General', max_length=100, null=True),
        ),
    ]
