# Generated by Django 6.0.4 on 2026-07-27 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # ('costanalysis', '0002_initial'),
        ('inventorypolicy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('safety_stock', models.PositiveIntegerField(default=0)),
                ('reorder_point', models.PositiveIntegerField(default=0)),
                ('reorder_quantity', models.PositiveIntegerField(default=0)),
                ('total_inventory_cost', models.FloatField()),
                ('recommendation', models.CharField(default='Not Best', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cost_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costanalysis.inventorycostanalysis')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventorypolicy.inventorypolicy')),
            ],
            options={
                'db_table': 'policy_comparison',
            },
        ),
    ]
