# Generated by Django 5.2.15 on 2026-08-14 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policycomparison', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policycomparison',
            name='overall_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='policycomparison',
            name='target_service_level',
            field=models.PositiveIntegerField(default=95),
        ),
        migrations.AlterField(
            model_name='policycomparison',
            name='recommendation',
            field=models.CharField(default='Not Recommended', max_length=50),
        ),
    ]
