# Generated by Django 5.2.15 on 2026-07-29 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard_title', models.CharField(default='Inventory Dashboard', max_length=100)),
                ('refresh_interval', models.PositiveIntegerField(default=30)),
                ('show_cost_chart', models.BooleanField(default=True)),
                ('show_simulation_chart', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dashboard Settings',
                'verbose_name_plural': 'Dashboard Settings',
                'db_table': 'dashboard_settings',
            },
        ),
    ]
