# Generated by Django 5.2.15 on 2026-07-29 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0002_initial'),
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_count', models.PositiveIntegerField(default=0)),
                ('supplier_count', models.PositiveIntegerField(default=0)),
                ('simulation_count', models.PositiveIntegerField(default=0)),
                ('total_inventory_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('holding_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ordering_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('stockout_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('service_level', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('inventory_turnover', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stockout_risk', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('average_inventory', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('total_stockouts', models.PositiveIntegerField(default=0)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_snapshots', to='Organization.organization')),
            ],
            options={
                'verbose_name': 'Dashboard Snapshot',
                'verbose_name_plural': 'Dashboard Snapshots',
                'db_table': 'dashboard_snapshot',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.DeleteModel(
            name='DashboardSettings',
        ),
    ]
