# Generated by Django 5.2.15 on 2026-07-29 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_dashboardsnapshot_delete_dashboardsettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DashboardSnapshot',
        ),
    ]
