# Generated by Django 6.0.4 on 2026-07-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('demand', models.PositiveIntegerField()),
                ('order_no', models.CharField(max_length=10)),
                ('lead_time', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'inventory',
            },
        ),
    ]
