# Generated by Django 5.2.14 on 2026-07-31 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventory_product'),
        ('product', '0002_product_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='admin',
            field=models.ForeignKey(db_column='admin_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventory',
            name='order_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(db_column='product_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='product.product'),
            preserve_default=False,
        ),
    ]
