# Generated by Django 5.2.14 on 2026-07-31 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_inventory_admin_alter_inventory_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='admin',
        ),
    ]
