# Generated by Django 5.2.14 on 2026-08-04 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_inventory_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='order_no',
        ),
    ]
