# Generated by Django 5.2.14 on 2026-08-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_inventory_order_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='date',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='demand',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='lead_time',
            field=models.JSONField(default=list),
        ),
    ]
