# Generated by Django 6.0.4 on 2026-08-05 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_historicalinventory'),
        ('inventory', '0009_alter_inventory_date_alter_inventory_demand_and_more'),
    ]

    operations = [
    ]
