# Generated by Django 5.2.15 on 2026-08-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_merge_20260805_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalinventory',
            name='order_no',
        ),
        migrations.AlterField(
            model_name='historicalinventory',
            name='date',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='historicalinventory',
            name='demand',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='historicalinventory',
            name='lead_time',
            field=models.JSONField(default=list),
        ),
    ]
