# Generated by Django 5.2.15 on 2026-08-05 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_merge_20260805_1239'),
        ('inventory', '0011_remove_historicalinventory_order_no_and_more'),
    ]

    operations = [
    ]
