# Generated by Django 5.2.15 on 2026-08-07 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_merge_20260805_1232'),
        ('inventory', '0012_merge_20260805_1734'),
    ]

    operations = [
    ]
