# Generated by Django 5.2.15 on 2026-08-11 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_merge_20260807_1623'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalInventory',
        ),
    ]
