# Generated by Django 6.0.4 on 2026-07-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_level', models.PositiveIntegerField()),
                ('z_value', models.FloatField()),
                ('average_demand', models.FloatField()),
                ('average_lead_time', models.FloatField()),
                ('safety_stock', models.PositiveIntegerField()),
                ('reorder_point', models.PositiveIntegerField()),
                ('reorder_quantity', models.PositiveIntegerField()),
                ('annual_demand', models.PositiveIntegerField()),
                ('ordering_cost', models.FloatField(default=0.0)),
                ('holding_cost', models.FloatField(default=0.0)),
                ('stockout_cost', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'inventory_policy',
            },
        ),
    ]
