# Generated by Django 5.2.15 on 2026-08-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorypolicy', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorypolicy',
            name='opening_stock',
            field=models.IntegerField(default=0),
        ),
    ]
