# Generated by Django 5.2.15 on 2026-08-05 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Organization', '0004_alter_organization_options'),
        ('product', '0005_remove_historicalproduct_opening_stock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_stock', models.IntegerField(default=0)),
                ('closing_stock', models.IntegerField(default=0)),
                ('total_demand', models.IntegerField(default=0)),
                ('total_orders', models.IntegerField(default=0)),
                ('stockout_days', models.IntegerField(default=0)),
                ('inventory_cost', models.FloatField(default=0)),
                ('average_inventory', models.FloatField(default=0)),
                ('service_level', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_summaries', to='Organization.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_summaries', to='product.product')),
            ],
            options={
                'db_table': 'inventory_summary',
                'ordering': ['-created_at'],
            },
        ),
    ]
