# Generated by Django 6.0.4 on 2026-08-04 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproduct',
            name='opening_stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='opening_stock',
        ),
    ]
