"""
Django settings for stocksim project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv

# Load environment variables from .env file
#load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#SECRET_KEY = 'django-insecure-!mw8b=dg8fss@n2(90lmoa5dia%z^k(-yprn$k8ah_tso3ailb'

SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = True
DEBUG = os.getenv("DEBUG", "False").lower() == "true"

# settings.py
#ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '*','10.168.111.32'] 
ALLOWED_HOSTS = os.getenv(
    "ALLOWED_HOSTS",
    "localhost,127.0.0.1"
).split(",")



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'authentication',
    'Organization',
    'suppliers',
    'product',
    'inventory',
    'probability',
    'inventorypolicy',
    'simulation',
    'costanalysis',
    'policycomparison',
    'dashboard',
    'inventorysummary',
    'reports',
    'subscriptions',
    'notifications.apps.NotificationsConfig',
    'auditlogs',
    'django_extensions',
    'corsheaders',
    
]
AUTH_USER_MODEL = 'authentication.CustomUser'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',

    'corsheaders.middleware.CorsMiddleware',

    'django.middleware.gzip.GZipMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3030",
    railway_url := os.getenv("RAILWAY_URL"),
    "http://127.0.0.1:3030",
    "http://10.168.111.32:3030",
]

ROOT_URLCONF = 'stocksim.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'stocksim.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT", "3306"),
        "OPTIONS": {
            "connect_timeout": 30,
        },
        'CONN_MAX_AGE': 600,
        'CONN_HEALTH_CHECKS': True,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

#STATIC_URL = 'static/'
STATIC_URL = "/static/"

STATIC_ROOT = BASE_DIR / "staticfiles"



# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
SIMPLE_HISTORY_HISTORY_ID_USE_UUID = True

# Razorpay Configuration (Test Mode)
import os

# Company Settings for GST Calculation
COMPANY_NAME = "StockSim Enterprise"
COMPANY_GST_NUMBER = "22AAAAA0000A1Z5"
COMPANY_STATE = "Telangana"
COMPANY_ADDRESS = "123 StockSim Towers, Hyderabad, Telangana"
COMPANY_CURRENCY = "INR"

DEFAULT_CGST_RATE = 9.0
DEFAULT_SGST_RATE = 9.0
DEFAULT_IGST_RATE = 18.0
EMAIL_PORT = 587
EMAIL_USE_TLS = True
#EMAIL_HOST_USER = "kalliswetha123@gmail.com"
#EMAIL_HOST_PASSWORD = "udwo dgaj geft ovrb"
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
EMAIL_TIMEOUT = 3

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# Twilio SMS Configurations
TWILIO_ACCOUNT_SID = "ACXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
TWILIO_AUTH_TOKEN = "your_auth_token_here"
TWILIO_PHONE_NUMBER = "+1234567890"





from datetime import timedelta


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'EXCEPTION_HANDLER': 'authentication.exceptions.custom_exception_handler',
}


PASSWORD_HASHERS = [
    'authentication.hashers.FastPBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
]

SIMPLE_JWT = {

    # Access Token expires in 30 minutes
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),

    # Refresh Token expires in 1 day
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),

    # Refresh token settings
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,

    # Update last login time
    "UPDATE_LAST_LOGIN": False,

    # JWT algorithm
    "ALGORITHM": "HS256",

    # Secret key
    "SIGNING_KEY": SECRET_KEY,

    # Authorization header format
    "AUTH_HEADER_TYPES": ("Bearer",),

    # Token class
    "AUTH_TOKEN_CLASSES": (
        "rest_framework_simplejwt.tokens.AccessToken",
    ),

    # CustomUser primary key field
    "USER_ID_FIELD": "admin_id",

    # JWT payload key
    "USER_ID_CLAIM": "user_id",
}



import os
from pathlib import Path
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")

#RAZORPAY_KEY_ID = os.getenv("RAZORPAY_KEY_ID", "rzp_test_qDsR8olKPMD3mL")
#RAZORPAY_KEY_SECRET = os.getenv("RAZORPAY_KEY_SECRET", "U7vjt9y7AiWs90470RK3qRQM")
RAZORPAY_KEY_ID = os.getenv("RAZORPAY_KEY_ID")
RAZORPAY_KEY_SECRET = os.getenv("RAZORPAY_KEY_SECRET")