# Generated by Django 5.2.15 on 2026-08-13 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventorypolicy', '0003_inventorypolicy_opening_stock'),
        ('product', '0006_delete_historicalproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCostAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simulation_days', models.PositiveIntegerField()),
                ('average_inventory', models.FloatField()),
                ('total_demand', models.PositiveIntegerField()),
                ('total_orders', models.PositiveIntegerField()),
                ('stockout_quantity', models.PositiveIntegerField()),
                ('holding_cost', models.FloatField()),
                ('ordering_cost', models.FloatField()),
                ('stockout_cost', models.FloatField()),
                ('total_inventory_cost', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('policy', models.ForeignKey(db_column='policy_id', on_delete=django.db.models.deletion.CASCADE, related_name='cost_analysis', to='inventorypolicy.inventorypolicy')),
                ('product', models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_analyses', to='product.product')),
            ],
            options={
                'db_table': 'inventory_cost_analysis',
            },
        ),
    ]
