# Generated by Django 6.0.4 on 2026-08-01 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_supplier'),
        ('suppliers', '0002_historicalsupplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsupplier',
            name='product',
            field=models.ForeignKey(blank=True, db_column='product_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='product.product'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='product',
            field=models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='product.product'),
        ),
    ]
