# Generated by Django 6.0.4 on 2026-08-04 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_historicalsupplier_product_supplier_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['supplier_id'], 'verbose_name': 'Supplier', 'verbose_name_plural': 'Suppliers'},
        ),
    ]
