# Generated by Django 5.2.15 on 2026-08-11 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0004_alter_supplier_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalSupplier',
        ),
    ]
