# Generated by Django 6.0.4 on 2026-07-27 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonteCarloSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField()),
                ('opening_stock', models.IntegerField()),
                ('random_demand', models.PositiveIntegerField()),
                ('simulated_demand', models.PositiveIntegerField()),
                ('closing_stock', models.IntegerField()),
                ('order_status', models.CharField(choices=[('No', 'No'), ('Order Placed', 'Order Placed'), ('Pending', 'Pending'), ('Received', 'Received')], default='No', max_length=20)),
                ('random_lead', models.PositiveIntegerField(blank=True, null=True)),
                ('simulated_lead', models.PositiveIntegerField(blank=True, null=True)),
                ('arrival_day', models.PositiveIntegerField(blank=True, null=True)),
                ('stock_received', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monte_carlo_simulations', to='product.product')),
            ],
            options={
                'db_table': 'monte_carlo_simulation',
                'ordering': ['day'],
            },
        ),
    ]
