# Generated by Django 6.0.4 on 2026-07-28 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorypolicy', '0002_initial'),
        ('simulation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='montecarlosimulation',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monte_carlo_simulations', to='inventorypolicy.inventorypolicy'),
        ),
    ]
