# Generated by Django 5.2.14 on 2026-08-04 07:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def drop_created_at(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("DELETE FROM monte_carlo_simulation;")
        try:
            cursor.execute("ALTER TABLE monte_carlo_simulation DROP COLUMN created_at;")
        except Exception:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('inventorypolicy', '0002_initial'),
        ('product', '0002_product_organization'),
        ('simulation', '0002_montecarlosimulation_policy'),
    ]

    operations = [
        migrations.RunPython(drop_created_at, reverse_code=migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name='montecarlosimulation',
            options={},
        ),
        migrations.AddField(
            model_name='montecarlosimulation',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='montecarlosimulation',
            name='arrival_day',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='montecarlosimulation',
            name='closing_stock',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='montecarlosimulation',
            name='day',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='montecarlosimulation',
            name='opening_stock',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='montecarlosimulation',
            name='order_status',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='montecarlosimulation',
            name='policy',
            field=models.ForeignKey(blank=True, db_column='policy_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventorypolicy.inventorypolicy'),
        ),
        migrations.AlterField(
            model_name='montecarlosimulation',
            name='product',
            field=models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AlterField(
            model_name='montecarlosimulation',
            name='random_demand',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='montecarlosimulation',
            name='random_lead',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='montecarlosimulation',
            name='simulated_demand',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='montecarlosimulation',
            name='simulated_lead',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='montecarlosimulation',
            name='stock_received',
            field=models.JSONField(default=list),
        ),
    ]
