# Generated by Django 5.2.14 on 2026-08-04 12:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorypolicy', '0002_initial'),
        ('product', '0002_product_organization'),
        ('simulation', '0003_alter_montecarlosimulation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='montecarlosimulation',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='montecarlosimulation',
            name='policy',
            field=models.ForeignKey(blank=True, db_column='policy_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monte_carlo_simulations', to='inventorypolicy.inventorypolicy'),
        ),
        migrations.AlterField(
            model_name='montecarlosimulation',
            name='product',
            field=models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monte_carlo_simulations', to='product.product'),
        ),
    ]
