# Generated by Django 5.2.15 on 2026-08-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0005_resequence_simulations'),
    ]

    operations = [
        migrations.AddField(
            model_name='montecarlosimulation',
            name='simulation_days',
            field=models.IntegerField(blank=True, default=30, null=True),
        ),
    ]
